name: 功能建议
description: 描述使用场景与希望改善的操作
body:
  - type: textarea
    id: problem
    attributes:
      label: 当前遇到什么问题
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 希望怎样改善
    validations:
      required: true
